### ISSUE TITLE
Tutorial error: core/demo_CH_buildsystem.py

### ISSUE THREAD

**Issue by h-pervez** [projectchrono/chrono#272] opened 2020-10-13 13:20 UTC
I see the following error when trying to run this example, any help is appreciated! Thanks

  File "C:\Users\pervez\Anaconda3\Lib\site-packages\pychrono\demos\core\demo_CH_buildsystem.py", line 77, in <module>
    my_system.GetContactContainer().ReportAllContacts(my_rep)

  File "C:\Users\pervez\Anaconda3\lib\site-packages\pychrono\core.py", line 25440, in ReportAllContacts
    return _core.ChContactContainer_ReportAllContacts(self, callback)

RuntimeError: SWIG director method error. Error detected when calling 'ReportContactCallback.OnReportContact'

**Comment by h-pervez** [comment] 2020-10-15 12:43
I used a conda install on Windows 7, and I currently have Python 3.8.3 installed. How do I check if the demo is consistent with Pychrono? Thanks!

**Comment by Benatti1991** [comment] 2020-10-15 15:45
Hi,
they look consistent, the problem appears to be related to our conda package, while I cannot reproduce it when building from sources. We are working on fixing it an we'll keep you posted.
Simone

**Comment by Benatti1991** [comment] 2020-10-19 13:40
Hi, 
the problem you experienced was due to the conda packages being built with SWIG 3. I changed to SWIG 4 and the develop packages work fine. Please install the develop version number 688 and let us know if the problem is solved so that we can close the issue.
Simone

**Comment by h-pervez** [comment] 2020-10-20 12:30
Hello Simone, this definitely solved the issue, the demo now works fine! Thanks :D

**Closed** 2020-10-20 12:56 UTC

**Comment by aditya-shirwatkar** [comment] 2021-05-26 06:29
@Benatti1991 @rserban I am facing the same issue.

![image](https://user-images.githubusercontent.com/50446525/119612543-a5cbf880-be19-11eb-9678-1da1d80bff5d.png)


`OS: Ubuntu 18.04`
`Python installation: conda install -c projectchrono/label/develop pychrono`
`Python Version: 3.7.10`
and I am running the demo python files on the current develop branch on GitHub



Thanks

**Comment by aditya-shirwatkar** [comment] 2021-05-26 07:28
> @Benatti1991 @rserban I am facing the same issue.
> 
> ![image](https://user-images.githubusercontent.com/50446525/119612543-a5cbf880-be19-11eb-9678-1da1d80bff5d.png)
> 
> `OS: Ubuntu 18.04`
> `Python installation: conda install -c projectchrono/label/develop pychrono`
> `Python Version: 3.7.10`
> and I am running the demo python files on the current develop branch on GitHub
> 
> Thanks
> 
> Update: `Python installation: conda install -c projectchrono pychrono` also produces the same error

On further inspection I found that files are generated using SWIG 3.0.12
![image](https://user-images.githubusercontent.com/50446525/119619534-bb452080-be21-11eb-813c-0dbb46bd7b7b.png)


You mentioned to use version 688 but there is no such version on conda repo here https://anaconda.org/projectchrono/pychrono/files

**Comment by Benatti1991** [comment] 2021-05-26 08:47
@aditya-shirwatkar the version numbers got reset after last February's release (6.0). Try to uninstall and reinstall pychrono develop, you should get 223 version.

**Comment by aditya-shirwatkar** [comment] 2021-05-26 09:27
> @aditya-shirwatkar the version numbers got reset after last February's release (6.0). Try to uninstall and reinstall pychrono develop, you should get 223 version.

I observed this
* For linux-64
 ![image](https://user-images.githubusercontent.com/50446525/119635824-ae302d80-be31-11eb-940d-9493b2d6c54d.png)
* For windows-64
![image](https://user-images.githubusercontent.com/50446525/119636789-9ad19200-be32-11eb-8129-c4430dbb578d.png)

Maybe this issue needs a fix for linux-64 versions

**Comment by Benatti1991** [comment] 2021-05-26 09:42
Good point, I thought Linux was using SWIG4, I'm gonna fix it soon.

**Comment by dummifiedme** [comment] 2022-08-05 17:01
Was it fixed?
I facing the same error on the same tutorial problem.

```
Traceback (most recent call last):
  File "/home/user/Desktop/Compund Bow/pyChrono Trial/demo_CH_buildsystem.py", line 77, in <module>
    my_system.GetContactContainer().ReportAllContacts(my_rep)
  File "/home/user/anaconda3/envs/chrono/lib/python3.10/site-packages/pychrono/core.py", line 26667, in ReportAllContacts
    return _core.ChContactContainer_ReportAllContacts(self, callback)
RuntimeError: SWIG director method error. Error detected when calling 'ReportContactCallback.OnReportContact'

```

`OS: Manjaro Linux`
`Python Installation; conda install -c projectchrono pychrono
`Python Version: 3.10.5`

**Comment by rserban** [comment] 2022-08-05 17:11
The conda packages are being worked on. We hope to have them ready shortly.
In the meantime, you can try to build PyChrono from sources.  Everything works fine in that case.

**Comment by dummifiedme** [comment] 2022-08-05 17:15
> In the meantime, you can try to build PyChrono from sources. Everything works fine in that case.

Just to make sure, we don't need anaconda if we build from source? (I am asking about it since I am a little low on root storage)
