### ISSUE TITLE
Broken on i386: error: use of overloaded operator '[]' is ambiguous (with operand types 'chrono::quaternion' and 'int')

### ISSUE THREAD

**Issue by yurivict** [projectchrono/chrono#158] opened 2019-05-18 22:25 UTC
log: http://beefy5.nyi.freebsd.org/data/120i386-default/501758/logs/chrono-4.0.0.89_1.log

**Comment by thepianoboy** [comment] 2019-05-20 16:53
Duplicate of #154

**Closed by thepianoboy** 2019-05-20 16:53 UTC
