### ISSUE TITLE
Project Chrono for games?

### ISSUE THREAD

**Issue by markusstephanides** [projectchrono/chrono#355] opened 2021-12-26 21:05 UTC
Hello!

I'm looking to develop a vehicle simulation and saw chrono which looked really promising. However after playing with some demos and implementing a basic example into my engine showed, that it doesn't take much to make chrono struggle . If I have 100 simple cubes falling onto a plane, as soon as collision occurs, chrono slows the application down really heavily. Talking about frame times of about 200ms. 

Also some demos are performing really poorly once the bodies hit the ground or collide with other bodies. 

Did I miss something or is chrono not meant to provide real-time physics?

Thanks!

**Comment by thepianoboy** [comment] 2022-05-20 16:01
Closing as duplicate of #136. 
Summary: Chrono aims to provide physically accurate simulations in a reasonable amount of time. Near-real time is possible for certain (often simple) simulations, but it is not necessarily a design goal for the project as a whole.

**Closed by thepianoboy** 2022-05-20 16:01 UTC
